# Generated by Django 2.2.5 on 2019-09-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niceplace',
            name='place',
        ),
        migrations.AddField(
            model_name='niceplace',
            name='name',
            field=models.CharField(default='d', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.NicePlace')),
            ],
        ),
    ]
