# Generated by Django 2.2.5 on 2019-09-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190917_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='place',
        ),
        migrations.AddField(
            model_name='country',
            name='niceplace',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.NicePlace'),
            preserve_default=False,
        ),
    ]
