# Generated by Django 2.2.5 on 2019-10-04 18:32

from django.db import migrations


def create_post_group_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in ['posters', 'viewers', 'editors']:
        Group.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191004_1636'),
    ]

    operations = [
        migrations.RunPython(create_post_group_permissions)
    ]
