# Generated by Django 2.2.5 on 2019-10-11 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191004_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLottie',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lottie_json', models.TextField()),
            ],
        ),
    ]
