# Generated by Django 2.2.5 on 2019-09-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='defaulttext', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
